### ISSUE TITLE
drag and drop works for simple lists, but it is breaking in tables with heavy data

### ISSUE THREAD

**Issue by lakshbhutani01** [isaacHagoel/solid-dnd-directive#10]
`ErrorFallback.jsx:15 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at reconcileArrays (http://localhost:3000/node_modules/.vite/deps/chunk-MNO6DYGY.js?v=f5e7b5dd:184:26)
    at insertExpression (http://localhost:3000/node_modules/.vite/deps/chunk-MNO6DYGY.js?v=f5e7b5dd:591:9)
    at Object.fn (http://localhost:3000/node_modules/.vite/deps/chunk-MNO6DYGY.js?v=f5e7b5dd:572:42)
    at runComputation (http://localhost:3000/node_modules/.vite/deps/chunk-5EDTS75K.js?v=f5e7b5dd:755:22)
    at updateComputation (http://localhost:3000/node_modules/.vite/deps/chunk-5EDTS75K.js?v=f5e7b5dd:738:3)
    at createRenderEffect (http://localhost:3000/node_modules/.vite/deps/chunk-5EDTS75K.js?v=f5e7b5dd:229:5)
    at insertExpression (http://localhost:3000/node_modules/.vite/deps/chunk-MNO6DYGY.js?v=f5e7b5dd:572:7)
    at Object.fn (http://localhost:3000/node_modules/.vite/deps/chunk-MNO6DYGY.js?v=f5e7b5dd:565:17)
    at runComputation (http://localhost:3000/node_modules/.vite/deps/chunk-5EDTS75K.js?v=f5e7b5dd:755:22)
    at updateComputation (http://localhost:3000/node_modules/.vite/deps/chunk-5EDTS75K.js?v=f5e7b5dd:738:3)`
   
   `Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at _createForOfIteratorHelper (index.mjs?v=f5e7b5dd:177:41)
    at unWatchDraggedElement (index.mjs?v=f5e7b5dd:1347:20)
    at handleDrop (index.mjs?v=f5e7b5dd:1540:3)
 `

**Comment by lakshbhutani01** [comment]
`Error: missing 'id' property for item {
  "isDndShadowItem": true
}
    at validateOptions (index.mjs?v=f5e7b5dd:2547:11)
    at update (index.mjs?v=f5e7b5dd:2505:7)
    at Object.updateOptionsAndTriggerFlip [as fn] (index.js?v=f5e7b5dd:22:13)
    at runComputation (dev.js:696:22)
    at updateComputation (dev.js:679:3)
    at runTop (dev.js:784:7)
    at runUserEffects (dev.js:882:36)
    at dev.js:851:34
    at runUpdates (dev.js:800:17)
    at completeUpdates (dev.js:851:17)`
